import type { FoundationFeatureModule } from '@/src/foundation/features/contracts';

export const foundationFeatureModules: readonly FoundationFeatureModule[] = [
  { featureKey: 'account.register', requiredMessageNamespaces: ['AuthPages'], requiredContentCollections: [] },
  { featureKey: 'account.passwordRecovery', requiredMessageNamespaces: ['AuthPages'], requiredContentCollections: [] },
  { featureKey: 'profiles.public', requiredMessageNamespaces: ['ProfilePage'], requiredContentCollections: [] },
  { featureKey: 'profiles.follow', requiredMessageNamespaces: ['ProfilePage'], requiredContentCollections: [] },
  { featureKey: 'profiles.blog', requiredMessageNamespaces: ['BlogPage'], requiredContentCollections: [] },
  { featureKey: 'people.directory', requiredMessageNamespaces: ['PeoplePage'], requiredContentCollections: [] },
  { featureKey: 'groups', requiredMessageNamespaces: ['GroupsPage'], requiredContentCollections: [] },
  { featureKey: 'notifications', requiredMessageNamespaces: ['NotificationsPage'], requiredContentCollections: [] },
  { featureKey: 'newsletter', requiredMessageNamespaces: [], requiredContentCollections: [] },
  { featureKey: 'reportProblem', requiredMessageNamespaces: ['ReportProblemPage'], requiredContentCollections: [] },
  { featureKey: 'content.blog', requiredMessageNamespaces: ['BlogPage'], requiredContentCollections: ['blog'] },
  { featureKey: 'content.changelog', requiredMessageNamespaces: [], requiredContentCollections: ['changelog'] },
  { featureKey: 'workspace.dataEntry', requiredMessageNamespaces: ['DataEntryPage'], requiredContentCollections: [] },
  { featureKey: 'admin.workspace', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'admin.content', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'admin.reports', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'admin.users', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'admin.systemSettings', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'admin.dataStudio', requiredMessageNamespaces: ['AdminPage'], requiredContentCollections: [] },
  { featureKey: 'showcase.forms', requiredMessageNamespaces: ['FormsPage'], requiredContentCollections: [] },
  { featureKey: 'showcase.story', requiredMessageNamespaces: ['StoryPage'], requiredContentCollections: [] },
  { featureKey: 'showcase.communication', requiredMessageNamespaces: ['CommunicationPage'], requiredContentCollections: [] },
  { featureKey: 'showcase.remocn', requiredMessageNamespaces: ['RemocnPage'], requiredContentCollections: [] },
  { featureKey: 'showcase.employeeTable', requiredMessageNamespaces: [], requiredContentCollections: [] },
  { featureKey: 'showcase.unlighthouse', requiredMessageNamespaces: ['UnlighthousePage'], requiredContentCollections: [] },
] as const;
