export const foundationFeatureKeys = [
  'account.register',
  'account.passwordRecovery',
  'profiles.public',
  'profiles.follow',
  'profiles.blog',
  'people.directory',
  'messages.direct',
  'notifications',
  'newsletter',
  'reportProblem',
  'content.blog',
  'content.changelog',
  'workspace.dataEntry',
  'admin.workspace',
  'admin.content',
  'admin.reports',
  'admin.users',
  'admin.systemSettings',
  'admin.dataStudio',
  'showcase.forms',
  'showcase.story',
  'showcase.communication',
  'showcase.uploads',
  'showcase.remocn',
  'showcase.employeeTable',
  'showcase.unlighthouse',
] as const;

export type FoundationFeatureKey = (typeof foundationFeatureKeys)[number];
