/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReportProblemRouteImport } from './routes/api/report-problem'
import { Route as ApiEmployeesRouteImport } from './routes/api/employees'
import { Route as LocalePublicRouteImport } from './routes/$locale/_public'
import { Route as LocaleAppRouteImport } from './routes/$locale/_app'
import { Route as LocalePublicIndexRouteImport } from './routes/$locale/_public/index'
import { Route as ApiProfileImageRouteImport } from './routes/api/profile/image'
import { Route as ApiProfileFollowRouteImport } from './routes/api/profile/follow'
import { Route as ApiProfileDisplayNameRouteImport } from './routes/api/profile/display-name'
import { Route as ApiNotificationsReadRouteImport } from './routes/api/notifications/read'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiExamplesEmployeesRouteImport } from './routes/api/examples/employees'
import { Route as ApiDataEntryRowsRouteImport } from './routes/api/data-entry/rows'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAnalyticsPageVisitsRouteImport } from './routes/api/analytics/page-visits'
import { Route as ApiAdminNotificationsRouteImport } from './routes/api/admin/notifications'
import { Route as ApiAccountVerifyEmailRouteImport } from './routes/api/account/verify-email'
import { Route as ApiAccountSignupRouteImport } from './routes/api/account/signup'
import { Route as ApiAccountResetPasswordRouteImport } from './routes/api/account/reset-password'
import { Route as ApiAccountForgotPasswordRouteImport } from './routes/api/account/forgot-password'
import { Route as ApiAccountEmailRouteImport } from './routes/api/account/email'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as LocalePublicVerifyEmailRouteImport } from './routes/$locale/_public/verify-email'
import { Route as LocalePublicUploadsRouteImport } from './routes/$locale/_public/uploads'
import { Route as LocalePublicTableRouteImport } from './routes/$locale/_public/table'
import { Route as LocalePublicStoryRouteImport } from './routes/$locale/_public/story'
import { Route as LocalePublicResetPasswordRouteImport } from './routes/$locale/_public/reset-password'
import { Route as LocalePublicReportProblemRouteImport } from './routes/$locale/_public/report-problem'
import { Route as LocalePublicRemocnRouteImport } from './routes/$locale/_public/remocn'
import { Route as LocalePublicFormsRouteImport } from './routes/$locale/_public/forms'
import { Route as LocalePublicCommunicationRouteImport } from './routes/$locale/_public/communication'
import { Route as LocalePublicAboutRouteImport } from './routes/$locale/_public/about'
import { Route as LocaleAppSettingsRouteImport } from './routes/$locale/_app/settings'
import { Route as LocaleAppRegisterRouteImport } from './routes/$locale/_app/register'
import { Route as LocaleAppProfileRouteImport } from './routes/$locale/_app/profile'
import { Route as LocaleAppNotificationsRouteImport } from './routes/$locale/_app/notifications'
import { Route as LocaleAppLoginRouteImport } from './routes/$locale/_app/login'
import { Route as LocaleAppDataEntryRouteImport } from './routes/$locale/_app/data-entry'
import { Route as LocaleAppAdminIndexRouteImport } from './routes/$locale/_app/admin/index'
import { Route as ApiProfileImageRemoveRouteImport } from './routes/api/profile/image/remove'
import { Route as ApiAdminReportsAuthorizationRouteImport } from './routes/api/admin/reports/authorization'
import { Route as ApiAdminDataStudioRecordsRouteImport } from './routes/api/admin/data-studio/records'
import { Route as LocalePublicProfileUserIdRouteImport } from './routes/$locale/_public/profile.$userId'
import { Route as LocalePublicExamplesUploadsRouteImport } from './routes/$locale/_public/examples.uploads'
import { Route as LocalePublicExamplesStoryRouteImport } from './routes/$locale/_public/examples.story'
import { Route as LocalePublicExamplesFormsRouteImport } from './routes/$locale/_public/examples.forms'
import { Route as LocalePublicExamplesCommunicationRouteImport } from './routes/$locale/_public/examples.communication'
import { Route as LocaleAppAdminUsersRouteImport } from './routes/$locale/_app/admin/users'
import { Route as LocaleAppAdminSystemSettingsRouteImport } from './routes/$locale/_app/admin/system-settings'
import { Route as LocaleAppAdminReportsRouteImport } from './routes/$locale/_app/admin/reports'
import { Route as LocaleAppAdminDataStudioRouteImport } from './routes/$locale/_app/admin/data-studio'
import { Route as LocaleAppAdminUsersUserIdRouteImport } from './routes/$locale/_app/admin/users.$userId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportProblemRoute = ApiReportProblemRouteImport.update({
  id: '/api/report-problem',
  path: '/api/report-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesRoute = ApiEmployeesRouteImport.update({
  id: '/api/employees',
  path: '/api/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePublicRoute = LocalePublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppRoute = LocaleAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePublicIndexRoute = LocalePublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalePublicRoute,
} as any)
const ApiProfileImageRoute = ApiProfileImageRouteImport.update({
  id: '/api/profile/image',
  path: '/api/profile/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileFollowRoute = ApiProfileFollowRouteImport.update({
  id: '/api/profile/follow',
  path: '/api/profile/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileDisplayNameRoute = ApiProfileDisplayNameRouteImport.update({
  id: '/api/profile/display-name',
  path: '/api/profile/display-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsReadRoute = ApiNotificationsReadRouteImport.update({
  id: '/api/notifications/read',
  path: '/api/notifications/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamplesEmployeesRoute = ApiExamplesEmployeesRouteImport.update({
  id: '/api/examples/employees',
  path: '/api/examples/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataEntryRowsRoute = ApiDataEntryRowsRouteImport.update({
  id: '/api/data-entry/rows',
  path: '/api/data-entry/rows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsPageVisitsRoute = ApiAnalyticsPageVisitsRouteImport.update({
  id: '/api/analytics/page-visits',
  path: '/api/analytics/page-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotificationsRoute = ApiAdminNotificationsRouteImport.update({
  id: '/api/admin/notifications',
  path: '/api/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountVerifyEmailRoute = ApiAccountVerifyEmailRouteImport.update({
  id: '/api/account/verify-email',
  path: '/api/account/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSignupRoute = ApiAccountSignupRouteImport.update({
  id: '/api/account/signup',
  path: '/api/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountResetPasswordRoute = ApiAccountResetPasswordRouteImport.update({
  id: '/api/account/reset-password',
  path: '/api/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountForgotPasswordRoute =
  ApiAccountForgotPasswordRouteImport.update({
    id: '/api/account/forgot-password',
    path: '/api/account/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountEmailRoute = ApiAccountEmailRouteImport.update({
  id: '/api/account/email',
  path: '/api/account/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePublicVerifyEmailRoute = LocalePublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicUploadsRoute = LocalePublicUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicTableRoute = LocalePublicTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicStoryRoute = LocalePublicStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicResetPasswordRoute =
  LocalePublicResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicReportProblemRoute =
  LocalePublicReportProblemRouteImport.update({
    id: '/report-problem',
    path: '/report-problem',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicRemocnRoute = LocalePublicRemocnRouteImport.update({
  id: '/remocn',
  path: '/remocn',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicFormsRoute = LocalePublicFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicCommunicationRoute =
  LocalePublicCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicAboutRoute = LocalePublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocaleAppSettingsRoute = LocaleAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppRegisterRoute = LocaleAppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppProfileRoute = LocaleAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppNotificationsRoute = LocaleAppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppLoginRoute = LocaleAppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppDataEntryRoute = LocaleAppDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAdminIndexRoute = LocaleAppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleAppRoute,
} as any)
const ApiProfileImageRemoveRoute = ApiProfileImageRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => ApiProfileImageRoute,
} as any)
const ApiAdminReportsAuthorizationRoute =
  ApiAdminReportsAuthorizationRouteImport.update({
    id: '/api/admin/reports/authorization',
    path: '/api/admin/reports/authorization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDataStudioRecordsRoute =
  ApiAdminDataStudioRecordsRouteImport.update({
    id: '/api/admin/data-studio/records',
    path: '/api/admin/data-studio/records',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocalePublicProfileUserIdRoute =
  LocalePublicProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicExamplesUploadsRoute =
  LocalePublicExamplesUploadsRouteImport.update({
    id: '/examples/uploads',
    path: '/examples/uploads',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicExamplesStoryRoute =
  LocalePublicExamplesStoryRouteImport.update({
    id: '/examples/story',
    path: '/examples/story',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicExamplesFormsRoute =
  LocalePublicExamplesFormsRouteImport.update({
    id: '/examples/forms',
    path: '/examples/forms',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicExamplesCommunicationRoute =
  LocalePublicExamplesCommunicationRouteImport.update({
    id: '/examples/communication',
    path: '/examples/communication',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocaleAppAdminUsersRoute = LocaleAppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAdminSystemSettingsRoute =
  LocaleAppAdminSystemSettingsRouteImport.update({
    id: '/admin/system-settings',
    path: '/admin/system-settings',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppAdminReportsRoute = LocaleAppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => LocaleAppRoute,
} as any)
const LocaleAppAdminDataStudioRoute =
  LocaleAppAdminDataStudioRouteImport.update({
    id: '/admin/data-studio',
    path: '/admin/data-studio',
    getParentRoute: () => LocaleAppRoute,
  } as any)
const LocaleAppAdminUsersUserIdRoute =
  LocaleAppAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => LocaleAppAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocalePublicRouteWithChildren
  '/about': typeof AboutRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale/data-entry': typeof LocaleAppDataEntryRoute
  '/$locale/login': typeof LocaleAppLoginRoute
  '/$locale/notifications': typeof LocaleAppNotificationsRoute
  '/$locale/profile': typeof LocaleAppProfileRoute
  '/$locale/register': typeof LocaleAppRegisterRoute
  '/$locale/settings': typeof LocaleAppSettingsRoute
  '/$locale/about': typeof LocalePublicAboutRoute
  '/$locale/communication': typeof LocalePublicCommunicationRoute
  '/$locale/forms': typeof LocalePublicFormsRoute
  '/$locale/remocn': typeof LocalePublicRemocnRoute
  '/$locale/report-problem': typeof LocalePublicReportProblemRoute
  '/$locale/reset-password': typeof LocalePublicResetPasswordRoute
  '/$locale/story': typeof LocalePublicStoryRoute
  '/$locale/table': typeof LocalePublicTableRoute
  '/$locale/uploads': typeof LocalePublicUploadsRoute
  '/$locale/verify-email': typeof LocalePublicVerifyEmailRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/examples/employees': typeof ApiExamplesEmployeesRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/': typeof LocalePublicIndexRoute
  '/$locale/admin/data-studio': typeof LocaleAppAdminDataStudioRoute
  '/$locale/admin/reports': typeof LocaleAppAdminReportsRoute
  '/$locale/admin/system-settings': typeof LocaleAppAdminSystemSettingsRoute
  '/$locale/admin/users': typeof LocaleAppAdminUsersRouteWithChildren
  '/$locale/examples/communication': typeof LocalePublicExamplesCommunicationRoute
  '/$locale/examples/forms': typeof LocalePublicExamplesFormsRoute
  '/$locale/examples/story': typeof LocalePublicExamplesStoryRoute
  '/$locale/examples/uploads': typeof LocalePublicExamplesUploadsRoute
  '/$locale/profile/$userId': typeof LocalePublicProfileUserIdRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
  '/$locale/admin/': typeof LocaleAppAdminIndexRoute
  '/$locale/admin/users/$userId': typeof LocaleAppAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocalePublicIndexRoute
  '/about': typeof AboutRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale/data-entry': typeof LocaleAppDataEntryRoute
  '/$locale/login': typeof LocaleAppLoginRoute
  '/$locale/notifications': typeof LocaleAppNotificationsRoute
  '/$locale/profile': typeof LocaleAppProfileRoute
  '/$locale/register': typeof LocaleAppRegisterRoute
  '/$locale/settings': typeof LocaleAppSettingsRoute
  '/$locale/about': typeof LocalePublicAboutRoute
  '/$locale/communication': typeof LocalePublicCommunicationRoute
  '/$locale/forms': typeof LocalePublicFormsRoute
  '/$locale/remocn': typeof LocalePublicRemocnRoute
  '/$locale/report-problem': typeof LocalePublicReportProblemRoute
  '/$locale/reset-password': typeof LocalePublicResetPasswordRoute
  '/$locale/story': typeof LocalePublicStoryRoute
  '/$locale/table': typeof LocalePublicTableRoute
  '/$locale/uploads': typeof LocalePublicUploadsRoute
  '/$locale/verify-email': typeof LocalePublicVerifyEmailRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/examples/employees': typeof ApiExamplesEmployeesRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/admin/data-studio': typeof LocaleAppAdminDataStudioRoute
  '/$locale/admin/reports': typeof LocaleAppAdminReportsRoute
  '/$locale/admin/system-settings': typeof LocaleAppAdminSystemSettingsRoute
  '/$locale/admin/users': typeof LocaleAppAdminUsersRouteWithChildren
  '/$locale/examples/communication': typeof LocalePublicExamplesCommunicationRoute
  '/$locale/examples/forms': typeof LocalePublicExamplesFormsRoute
  '/$locale/examples/story': typeof LocalePublicExamplesStoryRoute
  '/$locale/examples/uploads': typeof LocalePublicExamplesUploadsRoute
  '/$locale/profile/$userId': typeof LocalePublicProfileUserIdRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
  '/$locale/admin': typeof LocaleAppAdminIndexRoute
  '/$locale/admin/users/$userId': typeof LocaleAppAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/_app': typeof LocaleAppRouteWithChildren
  '/$locale/_public': typeof LocalePublicRouteWithChildren
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale/_app/data-entry': typeof LocaleAppDataEntryRoute
  '/$locale/_app/login': typeof LocaleAppLoginRoute
  '/$locale/_app/notifications': typeof LocaleAppNotificationsRoute
  '/$locale/_app/profile': typeof LocaleAppProfileRoute
  '/$locale/_app/register': typeof LocaleAppRegisterRoute
  '/$locale/_app/settings': typeof LocaleAppSettingsRoute
  '/$locale/_public/about': typeof LocalePublicAboutRoute
  '/$locale/_public/communication': typeof LocalePublicCommunicationRoute
  '/$locale/_public/forms': typeof LocalePublicFormsRoute
  '/$locale/_public/remocn': typeof LocalePublicRemocnRoute
  '/$locale/_public/report-problem': typeof LocalePublicReportProblemRoute
  '/$locale/_public/reset-password': typeof LocalePublicResetPasswordRoute
  '/$locale/_public/story': typeof LocalePublicStoryRoute
  '/$locale/_public/table': typeof LocalePublicTableRoute
  '/$locale/_public/uploads': typeof LocalePublicUploadsRoute
  '/$locale/_public/verify-email': typeof LocalePublicVerifyEmailRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/admin/notifications': typeof ApiAdminNotificationsRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/examples/employees': typeof ApiExamplesEmployeesRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/notifications/read': typeof ApiNotificationsReadRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/_public/': typeof LocalePublicIndexRoute
  '/$locale/_app/admin/data-studio': typeof LocaleAppAdminDataStudioRoute
  '/$locale/_app/admin/reports': typeof LocaleAppAdminReportsRoute
  '/$locale/_app/admin/system-settings': typeof LocaleAppAdminSystemSettingsRoute
  '/$locale/_app/admin/users': typeof LocaleAppAdminUsersRouteWithChildren
  '/$locale/_public/examples/communication': typeof LocalePublicExamplesCommunicationRoute
  '/$locale/_public/examples/forms': typeof LocalePublicExamplesFormsRoute
  '/$locale/_public/examples/story': typeof LocalePublicExamplesStoryRoute
  '/$locale/_public/examples/uploads': typeof LocalePublicExamplesUploadsRoute
  '/$locale/_public/profile/$userId': typeof LocalePublicProfileUserIdRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
  '/$locale/_app/admin/': typeof LocaleAppAdminIndexRoute
  '/$locale/_app/admin/users/$userId': typeof LocaleAppAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale/data-entry'
    | '/$locale/login'
    | '/$locale/notifications'
    | '/$locale/profile'
    | '/$locale/register'
    | '/$locale/settings'
    | '/$locale/about'
    | '/$locale/communication'
    | '/$locale/forms'
    | '/$locale/remocn'
    | '/$locale/report-problem'
    | '/$locale/reset-password'
    | '/$locale/story'
    | '/$locale/table'
    | '/$locale/uploads'
    | '/$locale/verify-email'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/admin/notifications'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/examples/employees'
    | '/api/newsletter/subscribe'
    | '/api/notifications/read'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/'
    | '/$locale/admin/data-studio'
    | '/$locale/admin/reports'
    | '/$locale/admin/system-settings'
    | '/$locale/admin/users'
    | '/$locale/examples/communication'
    | '/$locale/examples/forms'
    | '/$locale/examples/story'
    | '/$locale/examples/uploads'
    | '/$locale/profile/$userId'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
    | '/$locale/admin/'
    | '/$locale/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/about'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale/data-entry'
    | '/$locale/login'
    | '/$locale/notifications'
    | '/$locale/profile'
    | '/$locale/register'
    | '/$locale/settings'
    | '/$locale/about'
    | '/$locale/communication'
    | '/$locale/forms'
    | '/$locale/remocn'
    | '/$locale/report-problem'
    | '/$locale/reset-password'
    | '/$locale/story'
    | '/$locale/table'
    | '/$locale/uploads'
    | '/$locale/verify-email'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/admin/notifications'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/examples/employees'
    | '/api/newsletter/subscribe'
    | '/api/notifications/read'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/admin/data-studio'
    | '/$locale/admin/reports'
    | '/$locale/admin/system-settings'
    | '/$locale/admin/users'
    | '/$locale/examples/communication'
    | '/$locale/examples/forms'
    | '/$locale/examples/story'
    | '/$locale/examples/uploads'
    | '/$locale/profile/$userId'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
    | '/$locale/admin'
    | '/$locale/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/_app'
    | '/$locale/_public'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale/_app/data-entry'
    | '/$locale/_app/login'
    | '/$locale/_app/notifications'
    | '/$locale/_app/profile'
    | '/$locale/_app/register'
    | '/$locale/_app/settings'
    | '/$locale/_public/about'
    | '/$locale/_public/communication'
    | '/$locale/_public/forms'
    | '/$locale/_public/remocn'
    | '/$locale/_public/report-problem'
    | '/$locale/_public/reset-password'
    | '/$locale/_public/story'
    | '/$locale/_public/table'
    | '/$locale/_public/uploads'
    | '/$locale/_public/verify-email'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/admin/notifications'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/examples/employees'
    | '/api/newsletter/subscribe'
    | '/api/notifications/read'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/_public/'
    | '/$locale/_app/admin/data-studio'
    | '/$locale/_app/admin/reports'
    | '/$locale/_app/admin/system-settings'
    | '/$locale/_app/admin/users'
    | '/$locale/_public/examples/communication'
    | '/$locale/_public/examples/forms'
    | '/$locale/_public/examples/story'
    | '/$locale/_public/examples/uploads'
    | '/$locale/_public/profile/$userId'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
    | '/$locale/_app/admin/'
    | '/$locale/_app/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiEmployeesRoute: typeof ApiEmployeesRoute
  ApiReportProblemRoute: typeof ApiReportProblemRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountEmailRoute: typeof ApiAccountEmailRoute
  ApiAccountForgotPasswordRoute: typeof ApiAccountForgotPasswordRoute
  ApiAccountResetPasswordRoute: typeof ApiAccountResetPasswordRoute
  ApiAccountSignupRoute: typeof ApiAccountSignupRoute
  ApiAccountVerifyEmailRoute: typeof ApiAccountVerifyEmailRoute
  ApiAdminNotificationsRoute: typeof ApiAdminNotificationsRoute
  ApiAnalyticsPageVisitsRoute: typeof ApiAnalyticsPageVisitsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiDataEntryRowsRoute: typeof ApiDataEntryRowsRoute
  ApiExamplesEmployeesRoute: typeof ApiExamplesEmployeesRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  ApiNotificationsReadRoute: typeof ApiNotificationsReadRoute
  ApiProfileDisplayNameRoute: typeof ApiProfileDisplayNameRoute
  ApiProfileFollowRoute: typeof ApiProfileFollowRoute
  ApiProfileImageRoute: typeof ApiProfileImageRouteWithChildren
  ApiAdminDataStudioRecordsRoute: typeof ApiAdminDataStudioRecordsRoute
  ApiAdminReportsAuthorizationRoute: typeof ApiAdminReportsAuthorizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-problem': {
      id: '/api/report-problem'
      path: '/api/report-problem'
      fullPath: '/api/report-problem'
      preLoaderRoute: typeof ApiReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees': {
      id: '/api/employees'
      path: '/api/employees'
      fullPath: '/api/employees'
      preLoaderRoute: typeof ApiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_public': {
      id: '/$locale/_public'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalePublicRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_app': {
      id: '/$locale/_app'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAppRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_public/': {
      id: '/$locale/_public/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalePublicIndexRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/api/profile/image': {
      id: '/api/profile/image'
      path: '/api/profile/image'
      fullPath: '/api/profile/image'
      preLoaderRoute: typeof ApiProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/follow': {
      id: '/api/profile/follow'
      path: '/api/profile/follow'
      fullPath: '/api/profile/follow'
      preLoaderRoute: typeof ApiProfileFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/display-name': {
      id: '/api/profile/display-name'
      path: '/api/profile/display-name'
      fullPath: '/api/profile/display-name'
      preLoaderRoute: typeof ApiProfileDisplayNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/read': {
      id: '/api/notifications/read'
      path: '/api/notifications/read'
      fullPath: '/api/notifications/read'
      preLoaderRoute: typeof ApiNotificationsReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/examples/employees': {
      id: '/api/examples/employees'
      path: '/api/examples/employees'
      fullPath: '/api/examples/employees'
      preLoaderRoute: typeof ApiExamplesEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-entry/rows': {
      id: '/api/data-entry/rows'
      path: '/api/data-entry/rows'
      fullPath: '/api/data-entry/rows'
      preLoaderRoute: typeof ApiDataEntryRowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/page-visits': {
      id: '/api/analytics/page-visits'
      path: '/api/analytics/page-visits'
      fullPath: '/api/analytics/page-visits'
      preLoaderRoute: typeof ApiAnalyticsPageVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notifications': {
      id: '/api/admin/notifications'
      path: '/api/admin/notifications'
      fullPath: '/api/admin/notifications'
      preLoaderRoute: typeof ApiAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/verify-email': {
      id: '/api/account/verify-email'
      path: '/api/account/verify-email'
      fullPath: '/api/account/verify-email'
      preLoaderRoute: typeof ApiAccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/signup': {
      id: '/api/account/signup'
      path: '/api/account/signup'
      fullPath: '/api/account/signup'
      preLoaderRoute: typeof ApiAccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/reset-password': {
      id: '/api/account/reset-password'
      path: '/api/account/reset-password'
      fullPath: '/api/account/reset-password'
      preLoaderRoute: typeof ApiAccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/forgot-password': {
      id: '/api/account/forgot-password'
      path: '/api/account/forgot-password'
      fullPath: '/api/account/forgot-password'
      preLoaderRoute: typeof ApiAccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/email': {
      id: '/api/account/email'
      path: '/api/account/email'
      fullPath: '/api/account/email'
      preLoaderRoute: typeof ApiAccountEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_public/verify-email': {
      id: '/$locale/_public/verify-email'
      path: '/verify-email'
      fullPath: '/$locale/verify-email'
      preLoaderRoute: typeof LocalePublicVerifyEmailRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/uploads': {
      id: '/$locale/_public/uploads'
      path: '/uploads'
      fullPath: '/$locale/uploads'
      preLoaderRoute: typeof LocalePublicUploadsRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/table': {
      id: '/$locale/_public/table'
      path: '/table'
      fullPath: '/$locale/table'
      preLoaderRoute: typeof LocalePublicTableRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/story': {
      id: '/$locale/_public/story'
      path: '/story'
      fullPath: '/$locale/story'
      preLoaderRoute: typeof LocalePublicStoryRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/reset-password': {
      id: '/$locale/_public/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocalePublicResetPasswordRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/report-problem': {
      id: '/$locale/_public/report-problem'
      path: '/report-problem'
      fullPath: '/$locale/report-problem'
      preLoaderRoute: typeof LocalePublicReportProblemRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/remocn': {
      id: '/$locale/_public/remocn'
      path: '/remocn'
      fullPath: '/$locale/remocn'
      preLoaderRoute: typeof LocalePublicRemocnRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/forms': {
      id: '/$locale/_public/forms'
      path: '/forms'
      fullPath: '/$locale/forms'
      preLoaderRoute: typeof LocalePublicFormsRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/communication': {
      id: '/$locale/_public/communication'
      path: '/communication'
      fullPath: '/$locale/communication'
      preLoaderRoute: typeof LocalePublicCommunicationRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/about': {
      id: '/$locale/_public/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocalePublicAboutRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_app/settings': {
      id: '/$locale/_app/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleAppSettingsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/register': {
      id: '/$locale/_app/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleAppRegisterRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/profile': {
      id: '/$locale/_app/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleAppProfileRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/notifications': {
      id: '/$locale/_app/notifications'
      path: '/notifications'
      fullPath: '/$locale/notifications'
      preLoaderRoute: typeof LocaleAppNotificationsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/login': {
      id: '/$locale/_app/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleAppLoginRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/data-entry': {
      id: '/$locale/_app/data-entry'
      path: '/data-entry'
      fullPath: '/$locale/data-entry'
      preLoaderRoute: typeof LocaleAppDataEntryRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/admin/': {
      id: '/$locale/_app/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAppAdminIndexRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/api/profile/image/remove': {
      id: '/api/profile/image/remove'
      path: '/remove'
      fullPath: '/api/profile/image/remove'
      preLoaderRoute: typeof ApiProfileImageRemoveRouteImport
      parentRoute: typeof ApiProfileImageRoute
    }
    '/api/admin/reports/authorization': {
      id: '/api/admin/reports/authorization'
      path: '/api/admin/reports/authorization'
      fullPath: '/api/admin/reports/authorization'
      preLoaderRoute: typeof ApiAdminReportsAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data-studio/records': {
      id: '/api/admin/data-studio/records'
      path: '/api/admin/data-studio/records'
      fullPath: '/api/admin/data-studio/records'
      preLoaderRoute: typeof ApiAdminDataStudioRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_public/profile/$userId': {
      id: '/$locale/_public/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/$locale/profile/$userId'
      preLoaderRoute: typeof LocalePublicProfileUserIdRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/examples/uploads': {
      id: '/$locale/_public/examples/uploads'
      path: '/examples/uploads'
      fullPath: '/$locale/examples/uploads'
      preLoaderRoute: typeof LocalePublicExamplesUploadsRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/examples/story': {
      id: '/$locale/_public/examples/story'
      path: '/examples/story'
      fullPath: '/$locale/examples/story'
      preLoaderRoute: typeof LocalePublicExamplesStoryRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/examples/forms': {
      id: '/$locale/_public/examples/forms'
      path: '/examples/forms'
      fullPath: '/$locale/examples/forms'
      preLoaderRoute: typeof LocalePublicExamplesFormsRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/examples/communication': {
      id: '/$locale/_public/examples/communication'
      path: '/examples/communication'
      fullPath: '/$locale/examples/communication'
      preLoaderRoute: typeof LocalePublicExamplesCommunicationRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_app/admin/users': {
      id: '/$locale/_app/admin/users'
      path: '/admin/users'
      fullPath: '/$locale/admin/users'
      preLoaderRoute: typeof LocaleAppAdminUsersRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/admin/system-settings': {
      id: '/$locale/_app/admin/system-settings'
      path: '/admin/system-settings'
      fullPath: '/$locale/admin/system-settings'
      preLoaderRoute: typeof LocaleAppAdminSystemSettingsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/admin/reports': {
      id: '/$locale/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/$locale/admin/reports'
      preLoaderRoute: typeof LocaleAppAdminReportsRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/admin/data-studio': {
      id: '/$locale/_app/admin/data-studio'
      path: '/admin/data-studio'
      fullPath: '/$locale/admin/data-studio'
      preLoaderRoute: typeof LocaleAppAdminDataStudioRouteImport
      parentRoute: typeof LocaleAppRoute
    }
    '/$locale/_app/admin/users/$userId': {
      id: '/$locale/_app/admin/users/$userId'
      path: '/$userId'
      fullPath: '/$locale/admin/users/$userId'
      preLoaderRoute: typeof LocaleAppAdminUsersUserIdRouteImport
      parentRoute: typeof LocaleAppAdminUsersRoute
    }
  }
}

interface LocaleAppAdminUsersRouteChildren {
  LocaleAppAdminUsersUserIdRoute: typeof LocaleAppAdminUsersUserIdRoute
}

const LocaleAppAdminUsersRouteChildren: LocaleAppAdminUsersRouteChildren = {
  LocaleAppAdminUsersUserIdRoute: LocaleAppAdminUsersUserIdRoute,
}

const LocaleAppAdminUsersRouteWithChildren =
  LocaleAppAdminUsersRoute._addFileChildren(LocaleAppAdminUsersRouteChildren)

interface LocaleAppRouteChildren {
  LocaleAppDataEntryRoute: typeof LocaleAppDataEntryRoute
  LocaleAppLoginRoute: typeof LocaleAppLoginRoute
  LocaleAppNotificationsRoute: typeof LocaleAppNotificationsRoute
  LocaleAppProfileRoute: typeof LocaleAppProfileRoute
  LocaleAppRegisterRoute: typeof LocaleAppRegisterRoute
  LocaleAppSettingsRoute: typeof LocaleAppSettingsRoute
  LocaleAppAdminDataStudioRoute: typeof LocaleAppAdminDataStudioRoute
  LocaleAppAdminReportsRoute: typeof LocaleAppAdminReportsRoute
  LocaleAppAdminSystemSettingsRoute: typeof LocaleAppAdminSystemSettingsRoute
  LocaleAppAdminUsersRoute: typeof LocaleAppAdminUsersRouteWithChildren
  LocaleAppAdminIndexRoute: typeof LocaleAppAdminIndexRoute
}

const LocaleAppRouteChildren: LocaleAppRouteChildren = {
  LocaleAppDataEntryRoute: LocaleAppDataEntryRoute,
  LocaleAppLoginRoute: LocaleAppLoginRoute,
  LocaleAppNotificationsRoute: LocaleAppNotificationsRoute,
  LocaleAppProfileRoute: LocaleAppProfileRoute,
  LocaleAppRegisterRoute: LocaleAppRegisterRoute,
  LocaleAppSettingsRoute: LocaleAppSettingsRoute,
  LocaleAppAdminDataStudioRoute: LocaleAppAdminDataStudioRoute,
  LocaleAppAdminReportsRoute: LocaleAppAdminReportsRoute,
  LocaleAppAdminSystemSettingsRoute: LocaleAppAdminSystemSettingsRoute,
  LocaleAppAdminUsersRoute: LocaleAppAdminUsersRouteWithChildren,
  LocaleAppAdminIndexRoute: LocaleAppAdminIndexRoute,
}

const LocaleAppRouteWithChildren = LocaleAppRoute._addFileChildren(
  LocaleAppRouteChildren,
)

interface LocalePublicRouteChildren {
  LocalePublicAboutRoute: typeof LocalePublicAboutRoute
  LocalePublicCommunicationRoute: typeof LocalePublicCommunicationRoute
  LocalePublicFormsRoute: typeof LocalePublicFormsRoute
  LocalePublicRemocnRoute: typeof LocalePublicRemocnRoute
  LocalePublicReportProblemRoute: typeof LocalePublicReportProblemRoute
  LocalePublicResetPasswordRoute: typeof LocalePublicResetPasswordRoute
  LocalePublicStoryRoute: typeof LocalePublicStoryRoute
  LocalePublicTableRoute: typeof LocalePublicTableRoute
  LocalePublicUploadsRoute: typeof LocalePublicUploadsRoute
  LocalePublicVerifyEmailRoute: typeof LocalePublicVerifyEmailRoute
  LocalePublicIndexRoute: typeof LocalePublicIndexRoute
  LocalePublicExamplesCommunicationRoute: typeof LocalePublicExamplesCommunicationRoute
  LocalePublicExamplesFormsRoute: typeof LocalePublicExamplesFormsRoute
  LocalePublicExamplesStoryRoute: typeof LocalePublicExamplesStoryRoute
  LocalePublicExamplesUploadsRoute: typeof LocalePublicExamplesUploadsRoute
  LocalePublicProfileUserIdRoute: typeof LocalePublicProfileUserIdRoute
}

const LocalePublicRouteChildren: LocalePublicRouteChildren = {
  LocalePublicAboutRoute: LocalePublicAboutRoute,
  LocalePublicCommunicationRoute: LocalePublicCommunicationRoute,
  LocalePublicFormsRoute: LocalePublicFormsRoute,
  LocalePublicRemocnRoute: LocalePublicRemocnRoute,
  LocalePublicReportProblemRoute: LocalePublicReportProblemRoute,
  LocalePublicResetPasswordRoute: LocalePublicResetPasswordRoute,
  LocalePublicStoryRoute: LocalePublicStoryRoute,
  LocalePublicTableRoute: LocalePublicTableRoute,
  LocalePublicUploadsRoute: LocalePublicUploadsRoute,
  LocalePublicVerifyEmailRoute: LocalePublicVerifyEmailRoute,
  LocalePublicIndexRoute: LocalePublicIndexRoute,
  LocalePublicExamplesCommunicationRoute:
    LocalePublicExamplesCommunicationRoute,
  LocalePublicExamplesFormsRoute: LocalePublicExamplesFormsRoute,
  LocalePublicExamplesStoryRoute: LocalePublicExamplesStoryRoute,
  LocalePublicExamplesUploadsRoute: LocalePublicExamplesUploadsRoute,
  LocalePublicProfileUserIdRoute: LocalePublicProfileUserIdRoute,
}

const LocalePublicRouteWithChildren = LocalePublicRoute._addFileChildren(
  LocalePublicRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAppRoute: typeof LocaleAppRouteWithChildren
  LocalePublicRoute: typeof LocalePublicRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAppRoute: LocaleAppRouteWithChildren,
  LocalePublicRoute: LocalePublicRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface ApiProfileImageRouteChildren {
  ApiProfileImageRemoveRoute: typeof ApiProfileImageRemoveRoute
}

const ApiProfileImageRouteChildren: ApiProfileImageRouteChildren = {
  ApiProfileImageRemoveRoute: ApiProfileImageRemoveRoute,
}

const ApiProfileImageRouteWithChildren = ApiProfileImageRoute._addFileChildren(
  ApiProfileImageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiEmployeesRoute: ApiEmployeesRoute,
  ApiReportProblemRoute: ApiReportProblemRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountEmailRoute: ApiAccountEmailRoute,
  ApiAccountForgotPasswordRoute: ApiAccountForgotPasswordRoute,
  ApiAccountResetPasswordRoute: ApiAccountResetPasswordRoute,
  ApiAccountSignupRoute: ApiAccountSignupRoute,
  ApiAccountVerifyEmailRoute: ApiAccountVerifyEmailRoute,
  ApiAdminNotificationsRoute: ApiAdminNotificationsRoute,
  ApiAnalyticsPageVisitsRoute: ApiAnalyticsPageVisitsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiDataEntryRowsRoute: ApiDataEntryRowsRoute,
  ApiExamplesEmployeesRoute: ApiExamplesEmployeesRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  ApiNotificationsReadRoute: ApiNotificationsReadRoute,
  ApiProfileDisplayNameRoute: ApiProfileDisplayNameRoute,
  ApiProfileFollowRoute: ApiProfileFollowRoute,
  ApiProfileImageRoute: ApiProfileImageRouteWithChildren,
  ApiAdminDataStudioRecordsRoute: ApiAdminDataStudioRecordsRoute,
  ApiAdminReportsAuthorizationRoute: ApiAdminReportsAuthorizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
