/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as ApiReportProblemRouteImport } from './routes/api/report-problem'
import { Route as ApiEmployeesRouteImport } from './routes/api/employees'
import { Route as LocaleUploadsRouteImport } from './routes/$locale.uploads'
import { Route as LocaleTableRouteImport } from './routes/$locale.table'
import { Route as LocaleStoryRouteImport } from './routes/$locale.story'
import { Route as LocaleSettingsRouteImport } from './routes/$locale.settings'
import { Route as LocaleReportProblemRouteImport } from './routes/$locale.report-problem'
import { Route as LocaleRegisterRouteImport } from './routes/$locale.register'
import { Route as LocaleProfileRouteImport } from './routes/$locale.profile'
import { Route as LocaleNotificationsRouteImport } from './routes/$locale.notifications'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleFormsRouteImport } from './routes/$locale.forms'
import { Route as LocaleDataEntryRouteImport } from './routes/$locale.data-entry'
import { Route as LocaleCommunicationRouteImport } from './routes/$locale.communication'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale/admin/index'
import { Route as ApiProfileImageRouteImport } from './routes/api/profile/image'
import { Route as ApiProfileFollowRouteImport } from './routes/api/profile/follow'
import { Route as ApiProfileDisplayNameRouteImport } from './routes/api/profile/display-name'
import { Route as ApiDataEntryRowsRouteImport } from './routes/api/data-entry/rows'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAnalyticsPageVisitsRouteImport } from './routes/api/analytics/page-visits'
import { Route as ApiAccountVerifyEmailRouteImport } from './routes/api/account/verify-email'
import { Route as ApiAccountSignupRouteImport } from './routes/api/account/signup'
import { Route as ApiAccountResetPasswordRouteImport } from './routes/api/account/reset-password'
import { Route as ApiAccountForgotPasswordRouteImport } from './routes/api/account/forgot-password'
import { Route as ApiAccountEmailRouteImport } from './routes/api/account/email'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as LocaleProfileUserIdRouteImport } from './routes/$locale.profile.$userId'
import { Route as LocaleAdminUsersRouteImport } from './routes/$locale/admin/users'
import { Route as LocaleAdminSystemSettingsRouteImport } from './routes/$locale/admin/system-settings'
import { Route as LocaleAdminReportsRouteImport } from './routes/$locale/admin/reports'
import { Route as LocaleAdminDataStudioRouteImport } from './routes/$locale/admin/data-studio'
import { Route as ApiProfileImageRemoveRouteImport } from './routes/api/profile/image/remove'
import { Route as ApiAdminReportsAuthorizationRouteImport } from './routes/api/admin/reports/authorization'
import { Route as ApiAdminDataStudioRecordsRouteImport } from './routes/api/admin/data-studio/records'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiReportProblemRoute = ApiReportProblemRouteImport.update({
  id: '/api/report-problem',
  path: '/api/report-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesRoute = ApiEmployeesRouteImport.update({
  id: '/api/employees',
  path: '/api/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleUploadsRoute = LocaleUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTableRoute = LocaleTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleStoryRoute = LocaleStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReportProblemRoute = LocaleReportProblemRouteImport.update({
  id: '/report-problem',
  path: '/report-problem',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProfileRoute = LocaleProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleNotificationsRoute = LocaleNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFormsRoute = LocaleFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDataEntryRoute = LocaleDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCommunicationRoute = LocaleCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiProfileImageRoute = ApiProfileImageRouteImport.update({
  id: '/api/profile/image',
  path: '/api/profile/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileFollowRoute = ApiProfileFollowRouteImport.update({
  id: '/api/profile/follow',
  path: '/api/profile/follow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileDisplayNameRoute = ApiProfileDisplayNameRouteImport.update({
  id: '/api/profile/display-name',
  path: '/api/profile/display-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataEntryRowsRoute = ApiDataEntryRowsRouteImport.update({
  id: '/api/data-entry/rows',
  path: '/api/data-entry/rows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsPageVisitsRoute = ApiAnalyticsPageVisitsRouteImport.update({
  id: '/api/analytics/page-visits',
  path: '/api/analytics/page-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountVerifyEmailRoute = ApiAccountVerifyEmailRouteImport.update({
  id: '/api/account/verify-email',
  path: '/api/account/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSignupRoute = ApiAccountSignupRouteImport.update({
  id: '/api/account/signup',
  path: '/api/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountResetPasswordRoute = ApiAccountResetPasswordRouteImport.update({
  id: '/api/account/reset-password',
  path: '/api/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountForgotPasswordRoute =
  ApiAccountForgotPasswordRouteImport.update({
    id: '/api/account/forgot-password',
    path: '/api/account/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountEmailRoute = ApiAccountEmailRouteImport.update({
  id: '/api/account/email',
  path: '/api/account/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleProfileUserIdRoute = LocaleProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => LocaleProfileRoute,
} as any)
const LocaleAdminUsersRoute = LocaleAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminSystemSettingsRoute =
  LocaleAdminSystemSettingsRouteImport.update({
    id: '/admin/system-settings',
    path: '/admin/system-settings',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAdminReportsRoute = LocaleAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminDataStudioRoute = LocaleAdminDataStudioRouteImport.update({
  id: '/admin/data-studio',
  path: '/admin/data-studio',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiProfileImageRemoveRoute = ApiProfileImageRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => ApiProfileImageRoute,
} as any)
const ApiAdminReportsAuthorizationRoute =
  ApiAdminReportsAuthorizationRouteImport.update({
    id: '/api/admin/reports/authorization',
    path: '/api/admin/reports/authorization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDataStudioRecordsRoute =
  ApiAdminDataStudioRecordsRouteImport.update({
    id: '/api/admin/data-studio/records',
    path: '/api/admin/data-studio/records',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/communication': typeof LocaleCommunicationRoute
  '/$locale/data-entry': typeof LocaleDataEntryRoute
  '/$locale/forms': typeof LocaleFormsRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/notifications': typeof LocaleNotificationsRoute
  '/$locale/profile': typeof LocaleProfileRouteWithChildren
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/report-problem': typeof LocaleReportProblemRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/story': typeof LocaleStoryRoute
  '/$locale/table': typeof LocaleTableRoute
  '/$locale/uploads': typeof LocaleUploadsRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/data-studio': typeof LocaleAdminDataStudioRoute
  '/$locale/admin/reports': typeof LocaleAdminReportsRoute
  '/$locale/admin/system-settings': typeof LocaleAdminSystemSettingsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/profile/$userId': typeof LocaleProfileUserIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/communication': typeof LocaleCommunicationRoute
  '/$locale/data-entry': typeof LocaleDataEntryRoute
  '/$locale/forms': typeof LocaleFormsRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/notifications': typeof LocaleNotificationsRoute
  '/$locale/profile': typeof LocaleProfileRouteWithChildren
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/report-problem': typeof LocaleReportProblemRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/story': typeof LocaleStoryRoute
  '/$locale/table': typeof LocaleTableRoute
  '/$locale/uploads': typeof LocaleUploadsRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/data-studio': typeof LocaleAdminDataStudioRoute
  '/$locale/admin/reports': typeof LocaleAdminReportsRoute
  '/$locale/admin/system-settings': typeof LocaleAdminSystemSettingsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/profile/$userId': typeof LocaleProfileUserIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/admin': typeof LocaleAdminIndexRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/communication': typeof LocaleCommunicationRoute
  '/$locale/data-entry': typeof LocaleDataEntryRoute
  '/$locale/forms': typeof LocaleFormsRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/notifications': typeof LocaleNotificationsRoute
  '/$locale/profile': typeof LocaleProfileRouteWithChildren
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/report-problem': typeof LocaleReportProblemRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/$locale/story': typeof LocaleStoryRoute
  '/$locale/table': typeof LocaleTableRoute
  '/$locale/uploads': typeof LocaleUploadsRoute
  '/api/employees': typeof ApiEmployeesRoute
  '/api/report-problem': typeof ApiReportProblemRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/data-studio': typeof LocaleAdminDataStudioRoute
  '/$locale/admin/reports': typeof LocaleAdminReportsRoute
  '/$locale/admin/system-settings': typeof LocaleAdminSystemSettingsRoute
  '/$locale/admin/users': typeof LocaleAdminUsersRoute
  '/$locale/profile/$userId': typeof LocaleProfileUserIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/forgot-password': typeof ApiAccountForgotPasswordRoute
  '/api/account/reset-password': typeof ApiAccountResetPasswordRoute
  '/api/account/signup': typeof ApiAccountSignupRoute
  '/api/account/verify-email': typeof ApiAccountVerifyEmailRoute
  '/api/analytics/page-visits': typeof ApiAnalyticsPageVisitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/data-entry/rows': typeof ApiDataEntryRowsRoute
  '/api/profile/display-name': typeof ApiProfileDisplayNameRoute
  '/api/profile/follow': typeof ApiProfileFollowRoute
  '/api/profile/image': typeof ApiProfileImageRouteWithChildren
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/api/admin/data-studio/records': typeof ApiAdminDataStudioRecordsRoute
  '/api/admin/reports/authorization': typeof ApiAdminReportsAuthorizationRoute
  '/api/profile/image/remove': typeof ApiProfileImageRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/about'
    | '/$locale/communication'
    | '/$locale/data-entry'
    | '/$locale/forms'
    | '/$locale/login'
    | '/$locale/notifications'
    | '/$locale/profile'
    | '/$locale/register'
    | '/$locale/report-problem'
    | '/$locale/settings'
    | '/$locale/story'
    | '/$locale/table'
    | '/$locale/uploads'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale/'
    | '/$locale/admin/data-studio'
    | '/$locale/admin/reports'
    | '/$locale/admin/system-settings'
    | '/$locale/admin/users'
    | '/$locale/profile/$userId'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/admin/'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/$locale/about'
    | '/$locale/communication'
    | '/$locale/data-entry'
    | '/$locale/forms'
    | '/$locale/login'
    | '/$locale/notifications'
    | '/$locale/profile'
    | '/$locale/register'
    | '/$locale/report-problem'
    | '/$locale/settings'
    | '/$locale/story'
    | '/$locale/table'
    | '/$locale/uploads'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale'
    | '/$locale/admin/data-studio'
    | '/$locale/admin/reports'
    | '/$locale/admin/system-settings'
    | '/$locale/admin/users'
    | '/$locale/profile/$userId'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/admin'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/$locale/about'
    | '/$locale/communication'
    | '/$locale/data-entry'
    | '/$locale/forms'
    | '/$locale/login'
    | '/$locale/notifications'
    | '/$locale/profile'
    | '/$locale/register'
    | '/$locale/report-problem'
    | '/$locale/settings'
    | '/$locale/story'
    | '/$locale/table'
    | '/$locale/uploads'
    | '/api/employees'
    | '/api/report-problem'
    | '/$locale/'
    | '/$locale/admin/data-studio'
    | '/$locale/admin/reports'
    | '/$locale/admin/system-settings'
    | '/$locale/admin/users'
    | '/$locale/profile/$userId'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/forgot-password'
    | '/api/account/reset-password'
    | '/api/account/signup'
    | '/api/account/verify-email'
    | '/api/analytics/page-visits'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/data-entry/rows'
    | '/api/profile/display-name'
    | '/api/profile/follow'
    | '/api/profile/image'
    | '/$locale/admin/'
    | '/api/admin/data-studio/records'
    | '/api/admin/reports/authorization'
    | '/api/profile/image/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiEmployeesRoute: typeof ApiEmployeesRoute
  ApiReportProblemRoute: typeof ApiReportProblemRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountEmailRoute: typeof ApiAccountEmailRoute
  ApiAccountForgotPasswordRoute: typeof ApiAccountForgotPasswordRoute
  ApiAccountResetPasswordRoute: typeof ApiAccountResetPasswordRoute
  ApiAccountSignupRoute: typeof ApiAccountSignupRoute
  ApiAccountVerifyEmailRoute: typeof ApiAccountVerifyEmailRoute
  ApiAnalyticsPageVisitsRoute: typeof ApiAnalyticsPageVisitsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiDataEntryRowsRoute: typeof ApiDataEntryRowsRoute
  ApiProfileDisplayNameRoute: typeof ApiProfileDisplayNameRoute
  ApiProfileFollowRoute: typeof ApiProfileFollowRoute
  ApiProfileImageRoute: typeof ApiProfileImageRouteWithChildren
  ApiAdminDataStudioRecordsRoute: typeof ApiAdminDataStudioRecordsRoute
  ApiAdminReportsAuthorizationRoute: typeof ApiAdminReportsAuthorizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/report-problem': {
      id: '/api/report-problem'
      path: '/api/report-problem'
      fullPath: '/api/report-problem'
      preLoaderRoute: typeof ApiReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees': {
      id: '/api/employees'
      path: '/api/employees'
      fullPath: '/api/employees'
      preLoaderRoute: typeof ApiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/uploads': {
      id: '/$locale/uploads'
      path: '/uploads'
      fullPath: '/$locale/uploads'
      preLoaderRoute: typeof LocaleUploadsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/table': {
      id: '/$locale/table'
      path: '/table'
      fullPath: '/$locale/table'
      preLoaderRoute: typeof LocaleTableRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/story': {
      id: '/$locale/story'
      path: '/story'
      fullPath: '/$locale/story'
      preLoaderRoute: typeof LocaleStoryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/settings': {
      id: '/$locale/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/report-problem': {
      id: '/$locale/report-problem'
      path: '/report-problem'
      fullPath: '/$locale/report-problem'
      preLoaderRoute: typeof LocaleReportProblemRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/profile': {
      id: '/$locale/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleProfileRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/notifications': {
      id: '/$locale/notifications'
      path: '/notifications'
      fullPath: '/$locale/notifications'
      preLoaderRoute: typeof LocaleNotificationsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/forms': {
      id: '/$locale/forms'
      path: '/forms'
      fullPath: '/$locale/forms'
      preLoaderRoute: typeof LocaleFormsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/data-entry': {
      id: '/$locale/data-entry'
      path: '/data-entry'
      fullPath: '/$locale/data-entry'
      preLoaderRoute: typeof LocaleDataEntryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/communication': {
      id: '/$locale/communication'
      path: '/communication'
      fullPath: '/$locale/communication'
      preLoaderRoute: typeof LocaleCommunicationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/profile/image': {
      id: '/api/profile/image'
      path: '/api/profile/image'
      fullPath: '/api/profile/image'
      preLoaderRoute: typeof ApiProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/follow': {
      id: '/api/profile/follow'
      path: '/api/profile/follow'
      fullPath: '/api/profile/follow'
      preLoaderRoute: typeof ApiProfileFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/display-name': {
      id: '/api/profile/display-name'
      path: '/api/profile/display-name'
      fullPath: '/api/profile/display-name'
      preLoaderRoute: typeof ApiProfileDisplayNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-entry/rows': {
      id: '/api/data-entry/rows'
      path: '/api/data-entry/rows'
      fullPath: '/api/data-entry/rows'
      preLoaderRoute: typeof ApiDataEntryRowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/page-visits': {
      id: '/api/analytics/page-visits'
      path: '/api/analytics/page-visits'
      fullPath: '/api/analytics/page-visits'
      preLoaderRoute: typeof ApiAnalyticsPageVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/verify-email': {
      id: '/api/account/verify-email'
      path: '/api/account/verify-email'
      fullPath: '/api/account/verify-email'
      preLoaderRoute: typeof ApiAccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/signup': {
      id: '/api/account/signup'
      path: '/api/account/signup'
      fullPath: '/api/account/signup'
      preLoaderRoute: typeof ApiAccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/reset-password': {
      id: '/api/account/reset-password'
      path: '/api/account/reset-password'
      fullPath: '/api/account/reset-password'
      preLoaderRoute: typeof ApiAccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/forgot-password': {
      id: '/api/account/forgot-password'
      path: '/api/account/forgot-password'
      fullPath: '/api/account/forgot-password'
      preLoaderRoute: typeof ApiAccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/email': {
      id: '/api/account/email'
      path: '/api/account/email'
      fullPath: '/api/account/email'
      preLoaderRoute: typeof ApiAccountEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/profile/$userId': {
      id: '/$locale/profile/$userId'
      path: '/$userId'
      fullPath: '/$locale/profile/$userId'
      preLoaderRoute: typeof LocaleProfileUserIdRouteImport
      parentRoute: typeof LocaleProfileRoute
    }
    '/$locale/admin/users': {
      id: '/$locale/admin/users'
      path: '/admin/users'
      fullPath: '/$locale/admin/users'
      preLoaderRoute: typeof LocaleAdminUsersRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/system-settings': {
      id: '/$locale/admin/system-settings'
      path: '/admin/system-settings'
      fullPath: '/$locale/admin/system-settings'
      preLoaderRoute: typeof LocaleAdminSystemSettingsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/reports': {
      id: '/$locale/admin/reports'
      path: '/admin/reports'
      fullPath: '/$locale/admin/reports'
      preLoaderRoute: typeof LocaleAdminReportsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/data-studio': {
      id: '/$locale/admin/data-studio'
      path: '/admin/data-studio'
      fullPath: '/$locale/admin/data-studio'
      preLoaderRoute: typeof LocaleAdminDataStudioRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/profile/image/remove': {
      id: '/api/profile/image/remove'
      path: '/remove'
      fullPath: '/api/profile/image/remove'
      preLoaderRoute: typeof ApiProfileImageRemoveRouteImport
      parentRoute: typeof ApiProfileImageRoute
    }
    '/api/admin/reports/authorization': {
      id: '/api/admin/reports/authorization'
      path: '/api/admin/reports/authorization'
      fullPath: '/api/admin/reports/authorization'
      preLoaderRoute: typeof ApiAdminReportsAuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data-studio/records': {
      id: '/api/admin/data-studio/records'
      path: '/api/admin/data-studio/records'
      fullPath: '/api/admin/data-studio/records'
      preLoaderRoute: typeof ApiAdminDataStudioRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleProfileRouteChildren {
  LocaleProfileUserIdRoute: typeof LocaleProfileUserIdRoute
}

const LocaleProfileRouteChildren: LocaleProfileRouteChildren = {
  LocaleProfileUserIdRoute: LocaleProfileUserIdRoute,
}

const LocaleProfileRouteWithChildren = LocaleProfileRoute._addFileChildren(
  LocaleProfileRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleCommunicationRoute: typeof LocaleCommunicationRoute
  LocaleDataEntryRoute: typeof LocaleDataEntryRoute
  LocaleFormsRoute: typeof LocaleFormsRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleNotificationsRoute: typeof LocaleNotificationsRoute
  LocaleProfileRoute: typeof LocaleProfileRouteWithChildren
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleReportProblemRoute: typeof LocaleReportProblemRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleStoryRoute: typeof LocaleStoryRoute
  LocaleTableRoute: typeof LocaleTableRoute
  LocaleUploadsRoute: typeof LocaleUploadsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAdminDataStudioRoute: typeof LocaleAdminDataStudioRoute
  LocaleAdminReportsRoute: typeof LocaleAdminReportsRoute
  LocaleAdminSystemSettingsRoute: typeof LocaleAdminSystemSettingsRoute
  LocaleAdminUsersRoute: typeof LocaleAdminUsersRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleCommunicationRoute: LocaleCommunicationRoute,
  LocaleDataEntryRoute: LocaleDataEntryRoute,
  LocaleFormsRoute: LocaleFormsRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleNotificationsRoute: LocaleNotificationsRoute,
  LocaleProfileRoute: LocaleProfileRouteWithChildren,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleReportProblemRoute: LocaleReportProblemRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleStoryRoute: LocaleStoryRoute,
  LocaleTableRoute: LocaleTableRoute,
  LocaleUploadsRoute: LocaleUploadsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAdminDataStudioRoute: LocaleAdminDataStudioRoute,
  LocaleAdminReportsRoute: LocaleAdminReportsRoute,
  LocaleAdminSystemSettingsRoute: LocaleAdminSystemSettingsRoute,
  LocaleAdminUsersRoute: LocaleAdminUsersRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface ApiProfileImageRouteChildren {
  ApiProfileImageRemoveRoute: typeof ApiProfileImageRemoveRoute
}

const ApiProfileImageRouteChildren: ApiProfileImageRouteChildren = {
  ApiProfileImageRemoveRoute: ApiProfileImageRemoveRoute,
}

const ApiProfileImageRouteWithChildren = ApiProfileImageRoute._addFileChildren(
  ApiProfileImageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiEmployeesRoute: ApiEmployeesRoute,
  ApiReportProblemRoute: ApiReportProblemRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountEmailRoute: ApiAccountEmailRoute,
  ApiAccountForgotPasswordRoute: ApiAccountForgotPasswordRoute,
  ApiAccountResetPasswordRoute: ApiAccountResetPasswordRoute,
  ApiAccountSignupRoute: ApiAccountSignupRoute,
  ApiAccountVerifyEmailRoute: ApiAccountVerifyEmailRoute,
  ApiAnalyticsPageVisitsRoute: ApiAnalyticsPageVisitsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiDataEntryRowsRoute: ApiDataEntryRowsRoute,
  ApiProfileDisplayNameRoute: ApiProfileDisplayNameRoute,
  ApiProfileFollowRoute: ApiProfileFollowRoute,
  ApiProfileImageRoute: ApiProfileImageRouteWithChildren,
  ApiAdminDataStudioRecordsRoute: ApiAdminDataStudioRecordsRoute,
  ApiAdminReportsAuthorizationRoute: ApiAdminReportsAuthorizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
