name: Beta Tier

on:
  pull_request:
    branches: [beta]
  push:
    branches: [beta]

jobs:
  beta-tier:
    name: Beta Tier
    permissions:
      contents: read
      packages: read
    uses: moritzbrantner/reusable-workflows/.github/workflows/validate-repo.yml@scaffold-v2-initial
    with:
      test_command: bun run checks:beta
    secrets:
      node_auth_token: ${{ secrets.GH_PACKAGES_TOKEN }}
