name: Main Tier

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  main-tier:
    name: Main Tier
    permissions:
      contents: read
      packages: read
    uses: moritzbrantner/reusable-workflows/.github/workflows/validate-repo.yml@scaffold-v2-initial
    with:
      test_command: bun run checks:main
    secrets:
      node_auth_token: ${{ secrets.GH_PACKAGES_TOKEN }}
